import Head from 'next/head'
import Link from 'next/link'
import { Breadcrumb } from 'antd'
import { useContext } from 'react'
import {getAllProducts} from '@/lib/shopify'
import { CartContext } from '@/context/shopContext'
import InstructionSteps from '@/components/InstructionSteps'
import ProductCategoryList from '@/components/ProductCategoryList'

const categories = [
  {
    title: 'Sichtschutzzäune',
    url: '#',
    image: '/images/sichtschutzzaun.jpg',
    handle: 'sichtschutzzaune',
  },
]


const title = 'Willkommen beim Zaunplaner von hoerner-gmbh.com'
const stepOne = 'Wählen Sie im unteren Bereich eine Zaunvariante, je nachdem ob Sie einen Sichtschutz, einen Garten- oder Doppelstabzaun benötigen.'
const stepTwo = 'Bestimmen Sie nun das gewünschte Material und wählen die Zaunserie aus, deren Design Ihnen gefällt.'
const stepThree = 'Planen Sie Ihren Zaunverlauf, indem Sie die Zaunelemente aus der Übersicht auf die Rasenfläche ziehen. Länge und Preis werden immer angezeigt und mit nur einem Klick legen Sie den gesamten Zaun samt Zubehör in den Warenkorb.'

export default function Home({ products }) {

  const { addToCart } = useContext(CartContext)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col">
        <div className="container">

          <InstructionSteps
            title={title}
            stepOne={stepOne}
            stepTwo={stepTwo}
            stepThree={stepThree}
          />

          <Breadcrumb
            className="font-semibold"
            separator="/"
            items={[
              {
                title: 'Zaunvariante wählen',
              },
            ]}
          />

          <ul className="ProductCategoryList w-auto p-0 mt-5 mb-4 box-border">
            {categories.map((category, index) => (
              <Link href={`/product-category/${category.handle}`} key={index}>
                <ProductCategoryList
                  image={category.image}
                  title={category.title}
                  handle={category.handle}
                />
              </Link>
            ))}
          </ul>

          <h1>Produse Test</h1>

          <ul>
            {products.length > 0 &&
              products.map((product, index) => (
                <Link href={`/products/${product.node.handle}`} key={index}>
                  <ProductCategoryList
                    title={product.node.title}
                    image={product.node.images.edges[0].node.url}
                    handle={product.node.handle}
                    />
                </Link>
              ))}
          </ul>
          
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {

  const products = await getAllProducts()

  return {
    props: {
      products,
    },
  }
}
