import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

import {
  getAllProducts,
  getMainMenu,
  getProductsInCollection,
} from '@/lib/shopify'
import Link from 'next/link'
import ProductCategoryList from '@/components/ProductCategoryList'
import InstructionSteps from '@/components/InstructionSteps'

const inter = Inter({ subsets: ['latin'] })

const categories = [
  {
    title: 'Sichtschutzzäune',
    url: '#',
    image: '/images/sichtschutzzaun.jpg',
    handle: 'sichtschutzzaune',
  },
  {
    title: 'Gartenzäune',
    url: '#',
    image: '/images/gartenzaun.jpg ',
    handle: 'gartenmobel',
  },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <InstructionSteps />
          <h2 className="HeaderNav">Zaunvariante wählen</h2>
          <ul className="ProductCategoryList w-auto p-0 mt-0 mb-4 box-border">
            {categories.map((category, index) => (
              <Link href={`/product-category/${category.handle}`} key={index}>
                <ProductCategoryList
                  image={category.image}
                  title={category.title}
                  handle={category.handle}
                />
              </Link>
            ))}
          </ul>
        </div>
      </main>
      {/* <div className="container w-full">
        {products2.map((product) => (
          <div key={product.node.id}>
            <Link href={`products/${product.node.handle}`}>
              <h1>{product.node.title}</h1>
              <Image
                src={product?.node?.images?.edges[0].node.url}
                width={400}
                height={300}
                alt={product?.node?.title}
                priority
              />
            </Link>
          </div>
        ))}
      </div> */}
    </>
  )
}
